In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)


[1 2 3 4 5]


In [11]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])

print(np.concatenate([arr1,arr2], axis=1))

[[1 2 5 6]
 [3 4 7 8]]
